name: Max Area Test

on:
      pull_request:
          branches:
            - '*'
      push:
          branches:
            - 'master'

jobs:
      build:
        runs-on: windows-10 enterprise

        steps:
          - uses: actions/checkout@v3
          - name: Set up JDK 17
            uses: actions/setup-java@v3
            with:
              java-version: '17'
              distribution: 'temurin'

          - name: Test with gradle
            run: ./gradlew test --tests SolutionTest
