name: Max Area Test

on:
      pull_request:
          branches:
            - '*'
      push:
          branches:
            - 'master'

jobs:
      build:
        runs-on: windows-10 enterprise

        steps:
          - uses: actions/checkout@v4  # пише шо це вже застаріло
          - name: Set up JDK 17
            uses: actions/setup-java@v4 # пише шо це вже застаріло
            with:
              java-version: '17'
              distribution: 'temurin'

          - name: Test with gradle
            run: npm test
